DROP SEQUENCE SEQUTILISATEUR;
/
DROP SEQUENCE SEQDOCUMENT;
/
DROP SEQUENCE DOCUMENT;
/
DROP TABLE DOCUMENT;
/
DROP TABLE UTILISATEUR;
/

CREATE SEQUENCE SEQUTILISATEUR
MINVALUE 1
START WITH 1
INCREMENT BY 1
CACHE 20;

CREATE SEQUENCE SEQDOCUMENT
MINVALUE 1
START WITH 1
INCREMENT BY 1
CACHE 20;


CREATE TABLE DOCUMENT 
(
	IdDocument INTEGER PRIMARY KEY,
	NomDoc VARCHAR(30) NOT NULL,
	IsReserver INTEGER NOT NULL,
	IsDisponible INTEGER NOT NULL,
	UserID INTEGER
)
/

CREATE TABLE UTILISATEUR 
(
	IdUtilisateur INTEGER PRIMARY KEY,
	NomUtilisateur VARCHAR(30) NOT NULL,
	MotDePasse VARCHAR(30) NOT NULL,
	UserLogin VARCHAR(30) NOT NULL,
	TypeUtilisateur INTEGER NOT NULL
)
/

ALTER TABLE DOCUMENT ADD CONSTRAINT FK_ID_UTILISATEUR FOREIGN KEY (UserID) REFERENCES UTILISATEUR(IdUtilisateur);

INSERT INTO UTILISATEUR (IdUtilisateur,NomUtilisateur, MotDePasse,UserLogin, TypeUtilisateur) VALUES (SEQUTILISATEUR.NEXTVAL,'vadim','vadoom','vadime',1);
INSERT INTO UTILISATEUR (IdUtilisateur,NomUtilisateur, MotDePasse,UserLogin, TypeUtilisateur) VALUES (SEQUTILISATEUR.NEXTVAL,'Gerome','mdp','Jerome',0);

INSERT INTO DOCUMENT (IdDocument,NomDoc,isReserver, isDisponible, UserID) VALUES (SEQDOCUMENT.NEXTVAL,'Vadim mangea Vadoom',0,1,1);
INSERT INTO DOCUMENT (IdDocument,NomDoc,isReserver, isDisponible, UserID) VALUES (SEQDOCUMENT.NEXTVAL,'Vadim le fou',0,1,null);
INSERT INTO DOCUMENT (IdDocument,NomDoc,isReserver, isDisponible, UserID) VALUES (SEQDOCUMENT.NEXTVAL,'Il etait une fois Vadim',0,1,2);


commit;